name: garden_buddy
description: "Garden Buddy Flutter Adaptation"
publish_to: 'none'
version: 2.0.5+19

environment:
  sdk: '>=3.4.4 <4.0.0'

# Flutter dependencies
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shimmer: ^3.0.0
  google_mobile_ads: ^6.0.0
  image_picker: ^1.1.2
  dash_chat_2: ^0.0.21
  url_launcher: ^6.3.0
  camera: ^0.11.0+2
  purchases_flutter: ^8.1.5
  connectivity_plus: ^6.1.0
  swipe_refresh: ^1.1.2
  package_info_plus: ^8.1.2
  http: ^1.2.2
  camera_android: ^0.10.10
  sqflite: ^2.4.1
  path: ^1.9.0
  shared_preferences: ^2.5.2
  flutter_html: ^3.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# Flutter packages
flutter:
  uses-material-design: true

  # Assets
  assets:
    # Icons
    - assets/icons/icon.jpg
    - assets/icons/check_mark.png
    - assets/icons/cross_mark.png
    - assets/icons/gemini_icon.png
    - assets/icons/hand_plant_icon.png
    - assets/icons/health_assessment_icon.jpg
    - assets/icons/icons8_logo.png
    - assets/icons/identify_example_bad.jpg
    - assets/icons/identify_example_good.jpg
    - assets/icons/identify_icon.jpg
    - assets/icons/pixabay_icon.png
    - assets/icons/harvest.png
    - assets/icons/plant.png
    - assets/icons/pruning.png
    - assets/icons/seeds.png
    - assets/icons/sowing.png
    - assets/icons/watering.png
    - assets/icons/server_icon.png
    - assets/icons/hotpot_ai_icon.png
    - assets/icons/caterpillar.jpg
    - assets/icons/plant_addon.jpg
    - assets/icons/ai_icon.jpg

    # Images
    - assets/images/background_garden.jpg
    - assets/images/intro/database.png
    - assets/images/intro/ai_ex.gif
    - assets/images/intro/viewer.png

  # Fonts
  fonts:
    - family: Khand
      fonts:
        - asset: assets/fonts/khand_light.ttf
          weight: 100
        - asset: assets/fonts/khand_regular.ttf
          weight: 300
        - asset: assets/fonts/khand_bold.ttf
          weight: 700
